/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindMyRacketRouteImport } from './routes/find-my-racket'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ExploreRacketIdRouteImport } from './routes/explore.$racketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyRacketRoute = FindMyRacketRouteImport.update({
  id: '/find-my-racket',
  path: '/find-my-racket',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRacketIdRoute = ExploreRacketIdRouteImport.update({
  id: '/explore/$racketId',
  path: '/explore/$racketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-my-racket': typeof FindMyRacketRoute
  '/results': typeof ResultsRoute
  '/explore/$racketId': typeof ExploreRacketIdRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-my-racket': typeof FindMyRacketRoute
  '/results': typeof ResultsRoute
  '/explore/$racketId': typeof ExploreRacketIdRoute
  '/explore': typeof ExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-my-racket': typeof FindMyRacketRoute
  '/results': typeof ResultsRoute
  '/explore/$racketId': typeof ExploreRacketIdRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/find-my-racket' | '/results' | '/explore/$racketId' | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/find-my-racket' | '/results' | '/explore/$racketId' | '/explore'
  id:
    | '__root__'
    | '/'
    | '/find-my-racket'
    | '/results'
    | '/explore/$racketId'
    | '/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindMyRacketRoute: typeof FindMyRacketRoute
  ResultsRoute: typeof ResultsRoute
  ExploreRacketIdRoute: typeof ExploreRacketIdRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-racket': {
      id: '/find-my-racket'
      path: '/find-my-racket'
      fullPath: '/find-my-racket'
      preLoaderRoute: typeof FindMyRacketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$racketId': {
      id: '/explore/$racketId'
      path: '/explore/$racketId'
      fullPath: '/explore/$racketId'
      preLoaderRoute: typeof ExploreRacketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindMyRacketRoute: FindMyRacketRoute,
  ResultsRoute: ResultsRoute,
  ExploreRacketIdRoute: ExploreRacketIdRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
