update public.rackets as r set description = t.d from (values
('babolat-pure-aero-100','El referente de spin y potencia: velocidad de cabeza enorme y una respuesta muy viva.'),
('babolat-pure-aero-98','Aero de patrón más cerrado, hecha para spin pesado y controlado desde el fondo.'),
('babolat-pure-aero-plus','Monstruo de spin de largo extendido, para swings amplios y saques pesados.'),
('babolat-pure-drive','Potencia explosiva y profundidad fácil, sobre todo en el saque.'),
('babolat-pure-strike-98-16x19','Marco nítido y preciso, con sensación limpia y gran control direccional.'),
('babolat-pure-strike-98-18x20','Raqueta de control para pegadores planos, con patrón cerrado y salida muy predecible.'),
('dunlop-cx-200','Marco orientado al control, con sensación limpia y colocación confiable.'),
('dunlop-fx-500','Marco rápido y potente, con profundidad fácil y un punto dulce amplio.'),
('head-boom-mp','Ligera, cómoda y rápida: potencia accesible con respuesta suave.'),
('head-extreme-mp','Marco amigable con el spin, ángulo de salida alto y sensación moderna desde el fondo.'),
('head-gravity-mp','Marco de control orientado al confort, con punto dulce grande y suave.'),
('head-prestige-mp','Marco de control tradicional y pesado, con sensación profunda y enorme estabilidad.'),
('head-radical-mp','Marco equilibrado y versátil que hace casi todo bien, sin extremos.'),
('head-speed-mp','Marco all-court de manejo rápido que equilibra control, spin y velocidad de swing.'),
('head-speed-pro','Marco de jugador con patrón denso: cabeza de 100 con control cerrado y plano.'),
('prince-phantom-100x-18x20','Marco de perfil delgado muy flexible, con confort y toque excepcionales.'),
('tecnifibre-tf40-305','Marco de precisión ante todo, con sensación cómoda y conectada en golpes planos.'),
('tecnifibre-tfight-300-isoflex','Marco de jugador moderno, con garganta flexible y respuesta viva pero controlada.'),
('wilson-blade-100','Blade un poco más perdonadora, con salida más fácil y manejo ágil.'),
('wilson-blade-98-16x19','Marco de control de perfil cuadrado y flexible, con tacto suave y spin confiable.'),
('wilson-blade-98-18x20','Blade de patrón denso para pegadores de precisión que ponen su propia potencia.'),
('wilson-clash-100','Marco excepcionalmente flexible y amable con el brazo, de respuesta suave y perdonadora.'),
('wilson-pro-staff-97','Marco pesado, estable y de baja potencia para swings fuertes y compactos.'),
('wilson-pro-staff-x-100','Marco de control de 100 pulg² más pesado: estabilidad de raqueta de jugador con punto dulce mayor.'),
('wilson-shift-99','Marco flexible y latigueante, diseñado para empuñaduras extremas y topspin pesado.'),
('wilson-ultra-100','Marco potente y de profundidad fácil que premia swings cortos y el juego en la red.'),
('yonex-ezone-100','Marco de potencia cómodo y perdonador, ideal para jugadores en progreso y swings cortos.'),
('yonex-ezone-102','Sobredimensionada, ligera y perdonadora: punto dulce máximo y velocidad de swing fácil.'),
('yonex-ezone-98','Marco all-court cómodo, con punto dulce amplio y profundidad fácil para su tamaño de cabeza.'),
('yonex-percept-97','Marco de control flexible y con mucha sensación, premia swings largos y el toque en la red.'),
('yonex-vcore-100','Marco de spin de swing libre, con peso accesible y respuesta más viva que la 98.'),
('yonex-vcore-95','Marco de control y spin de cabeza pequeña, para jugadores avanzados con swings completos.'),
('yonex-vcore-98','Marco de control orientado al spin para quien pega rápido y busca pelotas pesadas que caen, sin perder penetración.')
) as t(slug, d) where r.slug = t.slug;